### ISSUE TITLE
Why TextField returns null

### ISSUE THREAD

**Issue by coffmark** [Ryosukekamimura/todoapp_by_flutter#1]
![8](https://user-images.githubusercontent.com/52638834/80293818-f21fb180-879d-11ea-9646-951abcea366c.jpg)

I entered text in the TextField but it was not transmitted.

What should i do?
Please tell me.

The whole source code is in this github, so please clone it.

**Comment by Ryosukekamimura** [comment]
I'm not sure what caused TextFeild to return null, but I run this program on Android Studio .
I could solve

[Stackoverflow answer](https://stackoverflow.com/questions/61434271/why-textfield-returns-null/61434485#61434485)
